on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Fallback
    steps:
      - name: Run test action
        id: test
        uses: samuraitruong/tf-actions@main
        with:
          token: ${{secrets.TF_TOKEN}}
          org_id: 'tnguyen'
          ws_name: 'tf-actions'
